controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...........2.2.2...222..........
        ..........4.4.4..225552.........
        .........2.2.2.225522252........
        ........4.4.4.4.252292252.......
        .........2.2.2.225522252........
        ..........4.4.4..225552.........
        ...........2.2.2...222..........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, hahah, 200, 0)
    music.pewPew.play()
})
function changeScore (Score: number) {
    info.changeScoreBy(Score)
    music.beamUp.play()
}
function gap () {
    if (info.score() > goal) {
        return "You reached your goal!"
    } else {
        return "You are " + (goal - info.score()) + "" + "your goal."
    }
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy()
    sprite.destroy(effects.fire, 500)
    changeScore(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.hearts, 500)
    info.changeLifeBy(-1)
})
let reachGoal = ""
let allien: Sprite = null
let projectile: Sprite = null
let hahah: Sprite = null
let goal = 0
goal = game.askForNumber("What is your goal score?", 3)
scene.setBackgroundColor(9)
hahah = sprites.create(img`
    ........................
    ........................
    ........................
    ...........ccc..........
    ...........cccc.........
    .......ccc..ccccccc.....
    .......cccccc555555cc...
    ........ccb5555555555c..
    .....cc..b555555555555c.
    .....cccb55555bcc555555c
    ......cb555555555c55d55c
    ......b5555555555555555c
    ...cc.b555dd5555bb1bbbc.
    ....ccd55ddddd55bbb335c.
    ...ccbddddddddd5bb3335c.
    .ccccdddddddddd55b3335c.
    cdcccdddddb55bbd553335c.
    cddbddddddb555bb55555c..
    cddddddddddb5555bbccc...
    ccddddddbd55bb55cbc.....
    .ccddddbbbdd55ccbdc.....
    ...ccbbbcbddddccdddc....
    .....ccccdd555dccccc....
    ........cccccccc........
    `, SpriteKind.Player)
controller.moveSprite(hahah, 200, 200)
hahah.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(500, function () {
    allien = sprites.create(img`
        ..............ffffff....
        .............f2feeeeff..
        ............f222feeeeff.
        .......cc...feeeeffeeef.
        .......cdc.fe2222eeffff.
        .......cddcf2effff222ef.
        ........cddcffeeefffffff
        .........cddce44fbe44eff
        ..........cdceddf14d4eef
        ..........cccdeddd4eeef.
        ...........edd4e44eeff..
        ............ee442222f...
        .............f2e2222f...
        .............f554444f...
        ..............ffffff....
        ................fff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    allien.setVelocity(-100, 0)
    allien.setPosition(160, randint(0, 120))
    if (info.life() == 0) {
        reachGoal = gap()
        game.splash(reachGoal)
    }
})
